name: CI

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: wiiznokes/io.github.wiiznokes.fan-control
          ref: master

      - run: |

          git remote add upstream https://github.com/flathub/io.github.wiiznokes.fan-control
          git fetch upstream
          git rebase upstream/master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7-rc
        with:
          title: "Automatic Release"
          base: master
          branch: release
          commit-message: "new release"
          body: ""
          delete-branch: true
          branch-suffix: short-commit-hash
          token: ${{ secrets.PAT_FLATHUB }}
